In [1]:
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

## Размерность массивов (1 балл)

Во всех заданиях этого блока **запрещается** руками модифицировать любые атрибуты массива.

In [2]:
a = np.ones(6, dtype=int)
a
a.shape

(6,)

* Превратите массив $a$ в вектор-строку `a.shape == (1, 6)`. Тип получившегося объекта по-прежнему должен быть `np.array`. **(0.25 балла)**

    **Запрещается** использовать `reshape`.

In [3]:
b = a[np.newaxis, :]
assert b.shape == (1, 6)
assert type(a) == type(b)

* Превратите массив $a$ в вектор-столбец `a.shape == (6, 1)`. Тип получившегося объекта по-прежнему должен быть `np.array`. **(0.25 балла)**

    **Запрещается** использовать `reshape`. Воспользуйтесь способом, который вы **НЕ** использовали в предыдущем пункте. Если в документации библиотеки он описан как эквивалентный, то этот способ подойдет.

In [4]:
c = np.expand_dims(a, axis=1)
assert c.shape == (6, 1)
assert type(a) == type(c)

* Превратите массив $a$ в массив $2 \times 3$. **(0.25 балла)**

In [5]:
d = np.reshape(a, newshape=(2, 3))
d

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
np.random.seed(7892)

cols = np.random.randint(low=10, high=20, size=1)
rows = 5

a = np.ones(cols * rows)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* Превратите массив $a$ в массив с 5 строками. **(0.25 балла)**

    **Запрещается** использовать информацию о размере массива $a$.

    **Разрешается** использовать переменную rows или число 5.

In [7]:
q = np.reshape(a, newshape=(rows, -1))
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Индексация (3.75 балла)

In [8]:
A = np.arange(36).reshape(-1, 6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

* Получите следующие подмассивы. **(по 0.25 балла за каждое задание; итого 1.25 балла за задание)**

    В первых 3-х индексациях **запрещается** использовать сложную индексацию.

    Поместите результат в перменную `A_slice`.

In [9]:
# put your code here
A_slice = A[2:5,2:5]

A_slice_res = np.array([[14, 15, 16],
                        [20, 21, 22],
                        [26, 27, 28]])

assert (A_slice == A_slice_res).all()

In [10]:
# put your code here
A_slice = A[3:,::2]

A_slice_res = np.array([[18, 20, 22],
                        [24, 26, 28],
                        [30, 32, 34]])

assert (A_slice == A_slice_res).all()

In [11]:
# put your code here
A_slice = A[-1:1:-1, 4:1:-1]

A_slice_res = np.array([[34, 33, 32],
                        [28, 27, 26],
                        [22, 21, 20],
                        [16, 15, 14]])

assert (A_slice == A_slice_res).all()

In [12]:
# put your code here
A_slice = A[::2, [1, 3, 4]]

A_slice_res = np.array([[ 1,  3,  4],
                        [13, 15, 16],
                        [25, 27, 28]])

assert (A_slice == A_slice_res).all()

In [13]:
# put your code here
A_slice = A[np.ix_([1, 3, 4], [1, 3, 4])]

A_slice_res = np.array([[ 7,  9, 10],
                        [19, 21, 22],
                        [25, 27, 28]])

assert (A_slice == A_slice_res).all()

* Создайте массив $A$ в виде [шахматной доски](https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D1%85%D0%BC%D0%B0%D1%82%D0%BD%D0%B0%D1%8F_%D0%B4%D0%BE%D1%81%D0%BA%D0%B0). **(0.25 балла)**

    **Подсказка:** задание решается с использованием индексации в несколько действий, не обязательно помещать все в одно выражение.

In [14]:
A = np.zeros(8 * 8).reshape(8, 8)
A[1::2, ::2] = 1
A[::2, 1::2] = 1

A_res = np.array([[0, 1, 0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0, 1, 0],
                  [0, 1, 0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0, 1, 0],
                  [0, 1, 0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0, 1, 0],
                  [0, 1, 0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0, 1, 0]])

assert (A == A_res).all()

* Возьмите столбцы, в которых есть хотя бы одно значение равно 7. **(0.25 балла)**

In [15]:
np.random.seed(7964)

A = np.random.randint(0, 8, size=(5, 5))
A[2, 3] = 10
A

array([[ 5,  6,  2,  4,  4],
       [ 1,  2,  3,  5,  0],
       [ 0,  2,  3, 10,  7],
       [ 2,  3,  6,  7,  7],
       [ 7,  3,  6,  2,  2]])

In [16]:
B = A[:, (A == 7).any(axis=0)]
B

array([[ 5,  4,  4],
       [ 1,  5,  0],
       [ 0, 10,  7],
       [ 2,  7,  7],
       [ 7,  2,  2]])

* Найдите индексы значений, которые меньше 4. **(0.25 балла)**

In [17]:
np.where(A < 4)

(array([0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4]),
 array([2, 0, 1, 2, 4, 0, 1, 2, 0, 1, 1, 3, 4]))

* Найдите индексы значений, которые меньше 4 и не меньше 2. **(0.25 балла)**

In [18]:
np.where((A >= 2) & (A < 4))

(array([0, 1, 1, 2, 2, 3, 3, 4, 4, 4]), array([2, 1, 2, 1, 2, 0, 1, 1, 3, 4]))

* Получите значения по этим индексам. **(0.25 балла)**

In [19]:
A[np.where((A >= 2) & (A < 4))]

array([2, 2, 3, 2, 3, 2, 3, 3, 2, 2])

* Найдите все индексы, где достигаются максимумы по строке в массиве $B$. **(0.5 балла)**

    **Подсказка:** `np.argmax` тут не подойдет. Почему?

In [20]:
B = [[0, 0, 3, 1, 3, 2],
     [2, 3, 0, 0, 3, 0],
     [0, 1, 2, 0, 0, 2],
     [2, 0, 2, 0, 2, 1],
     [1, 1, 0, 0, 1, 3]]
B = np.asarray(B)
B

array([[0, 0, 3, 1, 3, 2],
       [2, 3, 0, 0, 3, 0],
       [0, 1, 2, 0, 0, 2],
       [2, 0, 2, 0, 2, 1],
       [1, 1, 0, 0, 1, 3]])

In [21]:
C = np.expand_dims(B.max(axis=1), axis=1)
np.where(B == C)

(array([0, 0, 1, 1, 2, 2, 3, 3, 3, 4]), array([2, 4, 1, 4, 2, 5, 0, 2, 4, 5]))

* Рассмотрим массив $A$. Модифицируйте предыдущее решение так, чтобы получился массив $C$ следующего вида **(0.5 балла)**:
    * значения в матрице $C$ на позициях, где условие выполнено, совпадает со значениями на позициях в матрице $A$;
    * иначе – `-np.inf`.

  Сохраните результат в переменную $C$.

In [22]:
A = [[3, 1, 4, 5, 1, 2],
     [3, 3, 2, 4, 2, 2],
     [4, 1, 0, 1, 0, 2],
     [1, 0, 4, 3, 4, 3],
     [4, 2, 0, 1, 3, 4]]
A = np.asarray(A)
A

array([[3, 1, 4, 5, 1, 2],
       [3, 3, 2, 4, 2, 2],
       [4, 1, 0, 1, 0, 2],
       [1, 0, 4, 3, 4, 3],
       [4, 2, 0, 1, 3, 4]])

In [28]:
D = A.astype(float)
C = np.where(np.isclose(C, B), D, -np.inf)
C

array([[-inf, -inf,   4., -inf,   1., -inf],
       [-inf,   3., -inf, -inf,   2., -inf],
       [-inf, -inf,   0., -inf, -inf,   2.],
       [  1., -inf,   4., -inf,   4., -inf],
       [-inf, -inf, -inf, -inf, -inf,   4.]])

* Найдите индексы, где $C$ принимает наибольшие значения. **(0.25 балла)**

    **Замечание:** помните о том, что `C.dtype == dtype('float')`, и числа с плавующей точкой нельзя сравнивать через `==`.

In [31]:
np.where(np.isclose(C, C.max()))

(array([0, 3, 3, 4]), array([2, 2, 4, 5]))

## Операции над массивами (4.5 балла)

* Найдите максимальное значение в каждой строке массива $A$. **(0.25 балла)**

In [32]:
np.random.seed(7964)

A = np.random.randint(0, 8, size=(5, 5))
A[2, 3] = 10
A

array([[ 5,  6,  2,  4,  4],
       [ 1,  2,  3,  5,  0],
       [ 0,  2,  3, 10,  7],
       [ 2,  3,  6,  7,  7],
       [ 7,  3,  6,  2,  2]])

In [34]:
A.max(axis=1)

array([ 6,  5, 10,  7,  7])

* Найдите индексы максимального значения массива $A$. **(0.25 балла)**

    **Запрещается** считать координаты максимума руками. Найдите для этого специальную функцию.

In [ ]:
# put your code here

* Добавьте в массиве $A$ слева колонку, состоящую из 1. Сохраните свой результат в переменную $A$. **(0.25 балла)**

In [ ]:
# put your code here
# A = ...

In [ ]:
np.random.seed(7942)

W = (np.random.random(size=A.shape) > 0.5).astype(int)
W

* Умножьте массив $A$ на массив $W$ поэлементно. **(0.25 балла)**

In [ ]:
# put your code here

* Умножьте массив $A$ на массив $W^T$ матрично. **(0.25 балла)**

In [ ]:
# put your code here

In [ ]:
np.random.seed(4589)

X = np.random.randint(0, 2, size=(5, 10))
X

In [ ]:
x = np.arange(1, 11, 1)
x

* Найдите скалярное произведение вектора $x$ с каждым из 5 векторов массива $X$. **(0.25 балла)**

In [ ]:
# put your code here

* Отнормируйте столбцы массива $X$ по $l1$-норме. **(0.25 балла)**

In [ ]:
# put your code here

* Таблица умножения. Создайте массив $9 \times 9$, элементы которого являются произведениями индексов столбца и строки. **(0.5 балла)**

In [ ]:
# put your code here

In [ ]:
N, M = 5, 4

* Создайте массив с повторами. Разрешается использовать константы N и M. **(0.25 балла)**

    **Запрещается** использовать циклы.

In [ ]:
# put your code here

* Создайте массив с повторами. Разрешается использовать константы N и M. **(0.25 балла)**

    **Запрещается** использовать циклы.

In [ ]:
# put your code here

* Даны два небольших массива $A$ размера $M \times N$ и $B$ размера $K \times N$. 

    Напишите функцию `find_equal_lines(A, B)`, которая найдет все индексы строк массива $A$, содержащиеся в $B$.

    **Запрещается** использовать циклы. **(1 балл)**

    **Подсказка**: попробуйте поэкспериментировать с размерностью массивов $A$ и $B$.

In [ ]:
def find_equal_lines(A, B):
    # put your code here instead of pass
    pass

In [ ]:
A = np.array([
    [1, 2, 3],
    [1, 2, 1],
    [4, 5, 6],
    [1, 2, 1],
])

B = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [1, 2, 3],
])

indices = find_equal_lines(A, B)

assert (indices == [0, 2]).all()

### Изображения

In [ ]:
# Если у вас не получается скачать изображение с помощью этого кода, можете скачать его в ручную.
# Сохраните картинку рядом с этим ноутбуком и назовите image.jpg

import urllib.request 

urllib.request.urlretrieve(
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Prokudin-Gorskii-19.jpg/555px-Prokudin-Gorskii-19.jpg',
    'image.jpg'
)

In [ ]:
# Install package if it doesn't exist
# !pip install imageio

In [ ]:
import imageio

def plot_image(img, zoom=1.5):
    assert 2 <= len(img.shape) <= 3
    
    n_len = 6.5
    
    n, m = img.shape[:2]
    frac = n / float(m)
    n, m = zoom * frac * n_len, zoom * n_len
    
    fig = plt.figure(figsize=(n, m))
    ax = fig.add_subplot(111)
    ax.imshow(img)
    ax.axis('off')
    plt.show()

In [ ]:
img = imageio.imread('image.jpg')
plot_image(img, zoom=1.5)

* Найдите среднее значению по каждому из каналов RGB. **(0.25 балла)**

In [ ]:
# put your code here

* Посчитайте разброс (среднеквадратичное отклонение) значений по каждому из каналов. **(0.25 балла)**

In [ ]:
# put your code here

* Поменяйте каналы в обратном порядке. Сохраните результат в переменную img. **(0.25 балла)**

In [ ]:
# put your code here

In [ ]:
plot_image(img, zoom=1.5)

<center><h3>🎉 Ты уже прошёл больше половины пути. Вперед! 🎉</h3></center>

## Случайный классификатор (1.75 балла)

### Случайный классификатор

In [ ]:
from sklearn.base import ClassifierMixin

class RandomClassifier(ClassifierMixin):
    def __init__(self, n_classes=2, seed=8888):
        self.n_classes = n_classes
        self.seed = seed
    
    def fit(self, X, y=None):
        return self
    
    def predict_proba(self, X, y=None):
        """
        Method returns np.ndarray y:
            y.shape == (X.shape[0], n_classes)
        
        y satisfies:
            sum y[i, j] where j in {0..n_classes-1} = 1 
        """
        
        np.random.seed(self.seed)
        
        X = np.asarray(X)
        y = np.random.rand(X.shape[0], self.n_classes)
        y /= np.expand_dims(y.sum(axis=1), axis=1)
            
        return y
    
    def predict(self, X, y=None):
        y_pred = self.predict_proba(X)
        
        raise NotImplementedError('Code your realisation here')

In [ ]:
cls = RandomClassifier(n_classes=3, seed=3492)

X = list(range(100))
y_pred = cls.predict_proba(X)

y_pred.shape

* Убедитесь, что классификатор реализован правильно, т.е. сумма вероятностей для каждого примера из выборки равна 1.0. **(0.25 балла)**

    Для сравнения с 1.0 используйте функцию `np.isclose` или `np.allclose`. Ваша проверка должна иметь вид:

```python
assert condition
```

In [ ]:
# put your code here
# assert condition

* Для каждого примера из выборки найдите класс-победитель, реализуйте эту логику в методе `predict`. **(0.25 балла)**

In [ ]:
y_true = np.array([2, 0, 1, 1, 2, 0, 2, 1, 0, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 0, 0, 1,
                   2, 0, 0, 1, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 2, 1, 2, 2, 1, 2,
                   0, 2, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0,
                   1, 0, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 2, 0, 0, 1, 2, 1, 0,
                   0, 0, 2, 1, 1, 1, 0, 0, 2, 1, 1, 1])

y_pred = cls.predict(X)

assert (y_pred == y_true).all()

* Найдите количество примеров в каждом классе. **(0.25 балла)**

In [ ]:
# put your code here

* Напишите метрику LogLoss: **(0.25 балла)**

$$ LogLoss(y, p) = - y log(p) - (1 - y) log(1 - p) $$

* 
    * $y$ – истинная метка класса (0 или 1);
    * $p$ – предсказанная вероятность того, что объект пренадлежит классу 1.

$$ LogLoss = \frac{1}{N} \sum\limits_{i=1}^N LogLoss(y_i, p_i) $$

In [ ]:
def logloss(y_true, y_pred):
    """
    Функция возвращает усредненный лог-лосс для всех точек, см. последнюю формулу.
    """
    # put your code here instead of pass
    pass

In [ ]:
from sklearn.metrics import log_loss

cls = RandomClassifier(n_classes=2, seed=5498)

X = list(range(100))
y_pred = cls.predict_proba(X)[:,1]
y_true = (np.random.random(len(X)) > 0.5).astype(int)

score = logloss(y_true, y_pred)
assert np.allclose(score, log_loss(y_true, y_pred))

score

### Случайный регрессор

In [ ]:
from sklearn.base import RegressorMixin

class RandomRegressor(RegressorMixin):
    def __init__(self, seed=8888):
        self.seed = seed
    
    def fit(self, X, y=None):
        return self
    
    def predict(self, X, y=None):
        """
        Method returns np.ndarray y:
            y.shape == (X.shape[0], ) 
        """
        
        np.random.seed(self.seed)
        
        X = np.asarray(X)
        y = np.random.rand(X.shape[0])
        y = 2 * (y - 0.5)
            
        return y

* Напишите метрику MSE: **(0.25 балла)**

$$ MSE = \frac{1}{N} \sum\limits_{i=1}^{N} (y_i - \hat y_i) ^ 2 $$

* 
    * $y_i$ – истиное значение для i-го примера;
    * $\hat y_i$ – предсказанное значение для i-го примера.

In [ ]:
def mse(y_true, y_pred):
    # put your code here instead of pass
    pass

In [ ]:
from sklearn.metrics import mean_squared_error

reg = RandomRegressor(seed=5498)

X = list(range(100))
y_pred = reg.predict(X)
y_true = 2 * ((np.random.random(len(X)) > 0.5).astype(int) - 0.5)

score = mean_squared_error(y_true, y_pred)
assert np.allclose(score, mse(y_true, y_pred))

score

### Голосование

* Предположим, что мы используем набор из `K` различных классификаторов. Результаты работы классификаторов для `N` объектов хранятся в массиве `y_pred`, `y_pred.shape = (N, K)`.

    Требуется провести обычное голосование для каждого из объектов и выбрать метку-победитель (метка, встретившаяся для данного объекта наибольшее число раз). Если меток-победителей несколько, допустимо выбрать любую. **(0.5 балла)**

In [ ]:
np.random.seed(9866)

y_pred = np.random.randint(0, 3, size=(10, 5))
y_pred

In [ ]:
# put your code here

<center><h3>🎉 Ты почти дошел до конца! Осталось сделать ещё два сильных рывка! 🎉</h3></center>

## Ранжирование и сортировка (1.25 балла)

In [ ]:
# Если ваш компьютер не тянет такую большую матрицу разрешается
# понизить ее размеры, например, уменьшить число строк

np.random.seed(9872)

ranks_raw = [np.random.choice(50_000, size=(1_000, ), replace=False) for _ in range(3_000)]
ranks_raw = np.asarray(ranks_raw)
ranks_raw

In [ ]:
%%time

def get_best_ranks_slow(ranks, top=10, return_ranks=False):
    indices = ranks.argsort(axis=1)[:,:-top-1:-1]
    result = (indices, )
    
    if return_ranks:
        ranks = np.sort(ranks, axis=1)[:,:-top-1:-1]
        result += (ranks, )
        
    return result if len(result) > 1 else result[0]

indices_result = get_best_ranks_slow(ranks_raw, top=15)

* **Шаг 1: (0.25 балла)** 

    Напишите функцию `get_best_ranks(ranks, top=10)`, которая для каждой строчки выводит `top` индексов столбцов, в которых значение `ranks` максимально.

    Результат вашей функции должен быть равен результату работы `get_best_ranks_slow` быть может только за исключением порядка самих индексов в строках.

    **Замечание по реализации:** реализация приведенная выше неэффективна, сортировка работает за `O(N log(N))`. Приведите решение, которое работает за `O(N)`, где `N` – размер исходного массива.

    **Подсказка:** google "get indexes of n maximum values"

In [ ]:
%%time

def get_best_ranks(ranks, top=10):
    # put your code here instead of pass
    pass

indices = get_best_ranks(ranks_raw, top=15)

In [ ]:
assert (np.sort(indices, axis=1) == np.sort(indices_result, axis=1)).all()

* **Шаг 2: (0.5 балла)**

    Модифицируйте ваше решение, добавив в функцию сортировку так, чтобы результат работы функции `get_best_ranks` **в точности совпадал** с результатом работы функции `get_best_ranks_slow`. Приведите решение, которое работает за `O(N) + O(K log(K))`, где `N` – размер исходного массива, а `K` – число элементов в топе.

    **Замечание:** легко убедиться в том, что такое решение не улучшает асимптотику в смысле O-большого. Положим $K = a N; a \in (0, 1]$, тогда

    $$ O(K \log K) = O(a \cdot N \cdot \log(a \cdot N)) = \
   O(a N \cdot (\log a + \log N) = \
   O(a \cdot \log a \cdot N + a \cdot N \cdot \log N) = \
   O(N \log N)  $$
   
    Однако она зависит от константы $a$, поэтому такой вариант реализации работает быстрее, чем реализация `get_best_ranks_slow`.

In [ ]:
%%time

def get_best_ranks(ranks, top=10):
    # put your code here instead of pass
    pass

indices = get_best_ranks(ranks_raw, top=15)

In [ ]:
assert (indices == indices_result).all()

* **Шаг 3: (0.25 балла)**

    Поддержите в функции `get_best_ranks` аргумент `return_ranks=True`. В этом случае функция должна возвращать еще и значения ранков, см. реализацию `get_best_ranks_slow`.

    **Замечание:** поддержка аргумента не должна приводить к увеличению сложности, т.е. реализация в функции `get_best_ranks_slow` неверная.

In [ ]:
_, ranks_result = get_best_ranks_slow(ranks_raw, top=15, return_ranks=True)

In [ ]:
%%time

def get_best_ranks(ranks, top=10, return_ranks=False):
    # put your code here instead of pass
    pass

_, ranks = get_best_ranks(ranks_raw, top=15, return_ranks=True)

In [ ]:
assert np.isclose(ranks, ranks_result).all()

## Снежинка Коха (1 балл)

В этом задании предлагается поэтапно научиться строить фрактал [Снежинку Коха](https://en.wikipedia.org/wiki/Koch_snowflake).

<img src=https://i.pinimg.com/originals/fe/8f/26/fe8f26548e9c75575a0e0d25a88e58e4.jpg width=480px></img>

### Небольшое напоминание про компле́ксные числа.

Комплексным числом $z$ называется упорядоченная пара действительных чисел $(x, y); x, y \in \mathbb{R}$. Число $x$ называется действительной частью $z$, а число $y$ – мнимой частью числа $z$. Для них приняты следующие обозначения: $x = \text{Re}(z)$; $y = \text{Im}(z)$.

Множество комплексных чисел обозначается $\mathbb{C}$ (комплексная плоскость). Комплексное число $z$ можно интерпретировать как точку $(x, y)$ на комплексной плоскости.

Мнимой единицей называется комплексное число $i = (0, 1)$. Таким образом, число $z$ можно записать, как $$z = x + i y$$

Сопряженным к комплексному числу $z$ называется комплексное число $$\hat z = x - i y$$

Модулем комплексного числа $z$ называется $$|z| = \sqrt{x ^ 2 + y ^ 2}$$

Угол $\varphi$, составленный между точкой $z \ne 0$ и положительным направленим полуоси $Ox$, называется аргументом числа $z$. Аргумент числа $z$ определен с точностью до $2 \pi n$: $$ \text{Arg} z = \{ \varphi + 2 \pi n; n \in Z \} $$

Число $\varphi_0 = \varphi \in (-\pi; \pi]$ – называется главным аргументом числа $z$.

Если $\varphi \in \text{Arg} z$, то имеет место представление: $$ z = |z| (\cos \varphi + i \sin \varphi) $$

Используя формулу Эйлера $e^{i \varphi} = \cos \varphi + i \sin \varphi$ имеем $$z = |z| e ^ {i \varphi}$$

Пусть
$$ z_1 = x_1 + i y_1 = |z_1| e ^ {i \varphi_1} $$
$$ z_2 = x_2 + i y_2 = |z_2| e ^ {i \varphi_2} $$

Несколько важных свойств комплексных чисел:

* $z_1 \pm z_2 = (x_1 \pm x_2) + i (y_1 \pm y_2)$;
* $z_1 \cdot z_2 = (x_1 x_2 - y_1 y_2) + i (x_1 y_2 + x_2 y_1) = |z_1| |z_2| e ^ {i (\varphi_1 + \varphi_2)} $;
* $z_1 / z_2 = |z_1| / |z_2| e ^ {i (\varphi_1 - \varphi_2)} $;
* $z^n = |z|^n e ^ {i n \varphi} = |z| ^ n (\cos {n \varphi} + i \sin {n \varphi}), n \in \mathbb{Z}$ – формула Муавра-Лапласса.

Корнем $n$-й степени ($n \in \mathbb{N}$) из комплексного числа $z$ называется комплексное число $z_k^n$: $(z_k)^n = z$. В случае $z \ne 0$ имеем $n$ различных корней:

$$ z_k^n = |z|^{1/n} e ^ {i (\varphi + 2 \pi k) / n}; k \in \overline {0, n-1} $$

* **Шаг 1:** Напишите функцию, которая извлекает комплексный корень из 1. **(0.25 балла)**

In [ ]:
def complex_roots(n):
    # put your code here instead of pass
    pass

roots = complex_roots(5)
roots

In [ ]:
roots = np.append(roots, roots[0])

plt.figure(figsize=(5, 5))
plt.xlim(-1.1, 1.1)
plt.ylim(-1.1, 1.1)

plt.quiver(
    roots.real[:-1],
    roots.imag[:-1],
    roots.real[1:] - roots.real[:-1],
    roots.imag[1:] - roots.imag[:-1],
    scale_units='xy',
    angles='xy',
    scale=1,
    color='C0',
)

plt.show()

* **Шаг 2:** Напишите функцию, которая строит кривую Коха 1-го порядка. **(0.25 балла)**

    Разрешается захаркодить конкретные значения, но эти значения должны выражаться в виде правильной непериодической дроби.

    Например, дробь $1 \backslash 3$ допустима, а ее "округленный" вариант 0.666667 – нет.

In [ ]:
def koch_curve():
    # put your code here instead of pass
    pass

curve = koch_curve()
curve

In [ ]:
plt.figure(figsize=(5, 5))
plt.axis('equal')

plt.plot(curve.real, curve.imag)

plt.quiver(
    curve.real[:-1],
    curve.imag[:-1],
    curve.real[1:] - curve.real[:-1],
    curve.imag[1:] - curve.imag[:-1],
    scale_units='xy',
    angles='xy',
    scale=1,
    color='C0',
)

plt.show()

* **Шаг 3:** Заменим стороны в пятиугольнике выше на кривые Коха первого порядка. **(0.5 балла)**

    **Замечание:** Чтобы всё точно получилось, проверьте, что обход кривых на шагах 1 и 2 совпадает (либо в обоих сучаях по часовой, либо против).

In [ ]:
def change_edges_to_koch_curves(vertices):
    # put your code here instead of pass
    # use koch_curve function here
    pass

vertices = complex_roots(5)
line = change_edges_to_koch_curves(vertices)
line.shape

In [ ]:
line = np.concatenate([line, [line[0]]])

plt.figure(figsize=(5, 5))
plt.axis('equal')
plt.plot(line.real, line.imag)
plt.show()

* **Шаг 4:** Построим снежинку Коха.

In [ ]:
def koch_snowflake(order, scale=10):
    def _koch_snowflake_complex(order):
        if order == 0:
            vertices = complex_roots(3) * 1j
        else:
            vertices = _koch_snowflake_complex(order - 1)
            vertices = change_edges_to_koch_curves(vertices)
        return vertices

    points = scale * _koch_snowflake_complex(order)
    x, y = points.real, points.imag
    return x, y

x, y = koch_snowflake(order=5)

plt.figure(figsize=(8, 8))
plt.axis('equal')
plt.fill(x, y)
plt.show()

<center><h3>🎉 Поздравляю, ты справился с заданием по NumPy! Ты молодец! 🎉</h3></center>